using Compendium.Domain.SharedKernel;
using Compendium.Application.Classes;
using Compendium.Application.Features;
using Compendium.Application.Equipment;
using Compendium.Application.Fundamentals;
using Compendium.Application.Sources;
using Compendium.Application.Translations;
using Compendium.Application.Importing;
using Compendium.Domain.Importing;
using Compendium.Application.InternalQueries;
using Microsoft.Extensions.DependencyInjection;

namespace Compendium.Application;

public static class ApplicationDependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddSingleton<IClock, SystemClock>();
        services.AddScoped<CreateRulesetUseCase>();
        services.AddScoped<UpdateRulesetUseCase>();
        services.AddScoped<GetRulesetByCodeQuery>();
        services.AddScoped<CreateRuleSourceUseCase>();
        services.AddScoped<ActivateRuleSourceUseCase>();
        services.AddScoped<DeactivateRuleSourceUseCase>();
        services.AddScoped<ListRuleSourcesByRulesetQuery>();
        services.AddScoped<CreateSourceVersionUseCase>();
        services.AddScoped<MarkSourceVersionAsCurrentUseCase>();
        services.AddScoped<GetCurrentSourceVersionQuery>();
        services.AddScoped<ListSourceVersionsQuery>();
        services.AddScoped<CreateAbilityUseCase>();
        services.AddScoped<UpdateAbilityUseCase>();
        services.AddScoped<ListAbilitiesQuery>();
        services.AddScoped<CreateSkillUseCase>();
        services.AddScoped<UpdateSkillUseCase>();
        services.AddScoped<ListSkillsQuery>();
        services.AddScoped<CreateLanguageUseCase>();
        services.AddScoped<UpdateLanguageUseCase>();
        services.AddScoped<ListLanguagesQuery>();
        services.AddScoped<CreateProficiencyUseCase>();
        services.AddScoped<UpdateProficiencyUseCase>();
        services.AddScoped<ListProficienciesQuery>();
        services.AddScoped<CreateArmorTrainingCategoryUseCase>();
        services.AddScoped<ListArmorTrainingCategoriesQuery>();
        services.AddScoped<CreateHitDieUseCase>();
        services.AddScoped<ListHitDiceQuery>();
        services.AddScoped<CreateAbilityScoreMethodUseCase>();
        services.AddScoped<ListAbilityScoreMethodsQuery>();
        services.AddScoped<CreateClassUseCase>();
        services.AddScoped<UpdateClassUseCase>();
        services.AddScoped<ListClassesQuery>();
        services.AddScoped<GetClassDetailsQuery>();
        services.AddScoped<ConfigureClassProgressionUseCase>();
        services.AddScoped<GetClassProgressionQuery>();
        services.AddScoped<CreateSubclassUseCase>();
        services.AddScoped<LinkSubclassFeatureUseCase>();
        services.AddScoped<ListSubclassesByClassQuery>();
        services.AddScoped<GetSubclassDetailsQuery>();
        services.AddScoped<CreateFeatureUseCase>();
        services.AddScoped<UpdateFeatureUseCase>();
        services.AddScoped<ListFeaturesQuery>();
        services.AddScoped<GetFeatureDetailsQuery>();
        services.AddScoped<CreateEffectSchemaUseCase>();
        services.AddScoped<AttachEffectToFeatureUseCase>();
        services.AddScoped<GetFeatureEffectsQuery>();
        services.AddScoped<AddPrerequisiteToEntityUseCase>();
        services.AddScoped<RemovePrerequisiteFromEntityUseCase>();
        services.AddScoped<GetEntityPrerequisitesQuery>();
        services.AddScoped<CreateChoiceSetUseCase>();
        services.AddScoped<AddChoiceOptionUseCase>();
        services.AddScoped<AddChoiceFilterUseCase>();
        services.AddScoped<GetChoiceSetDetailsQuery>();
        services.AddScoped<ListChoiceSetsBySourceEntityQuery>();
        services.AddScoped<CreateEquipmentItemUseCase>();
        services.AddScoped<UpdateEquipmentItemUseCase>();
        services.AddScoped<ListEquipmentItemsQuery>();
        services.AddScoped<GetEquipmentItemDetailsQuery>();
        services.AddScoped<CreateWeaponUseCase>();
        services.AddScoped<AttachWeaponPropertyUseCase>();
        services.AddScoped<CreateWeaponPropertyUseCase>();
        services.AddScoped<ConfigureWeaponMasteryUseCase>();
        services.AddScoped<ListWeaponsQuery>();
        services.AddScoped<GetWeaponDetailsQuery>();
        services.AddScoped<CreateArmorUseCase>();
        services.AddScoped<ConfigureArmorAcRuleUseCase>();
        services.AddScoped<ListArmorsQuery>();
        services.AddScoped<GetArmorDetailsQuery>();
        services.AddScoped<CreateToolUseCase>();
        services.AddScoped<CreateEquipmentPackUseCase>();
        services.AddScoped<CreateStartingEquipmentRuleUseCase>();
        services.AddScoped<GetStartingEquipmentRuleQuery>();
        services.AddScoped<UpsertTranslationUseCase>();
        services.AddScoped<GetTranslationsForEntityQuery>();
        services.AddScoped<GetLocalizedEntityTranslationsQuery>();
        services.AddSingleton<CompendiumConsistencyChecker>();
        services.AddScoped<ImportSourceVersionUseCase>();
        services.AddScoped<ValidateSourceVersionUseCase>();
        services.AddScoped<ListSourceVersionValidationIssuesQuery>();
        services.AddScoped<GetCharacterCreationOptionsQuery>();
        services.AddScoped<GetMechanicalEntityDetailsQuery>();
        services.AddScoped<ListCompendiumChangesSinceQuery>();

        return services;
    }
}
