// <auto-generated />
using System;
using Compendium.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Compendium.Infra.Persistence.Migrations
{
    [DbContext(typeof(CompendiumDbContext))]
    [Migration("20260724172754_AddFeaturesEffectsPrerequisitesAndChoices")]
    partial class AddFeaturesEffectsPrerequisitesAndChoices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("compendium")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Compendium.Domain.Classes.CharacterClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("RuleSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_source_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_classes_code");

                    b.HasIndex("SourceVersionId")
                        .HasDatabaseName("ix_classes_source_version_id");

                    b.ToTable("classes", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.CharacterSubclass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_class_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("RuleSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_source_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_subclasses");

                    b.HasIndex("CharacterClassId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_subclasses_class_code");

                    b.ToTable("subclasses", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassCoreTraits", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArmorTrainingCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("armor_training_category_id");

                    b.Property<Guid>("CharacterClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_class_id");

                    b.Property<Guid>("HitDieId")
                        .HasColumnType("uuid")
                        .HasColumnName("hit_die_id");

                    b.Property<int>("SkillChoiceCount")
                        .HasColumnType("integer")
                        .HasColumnName("skill_choice_count");

                    b.HasKey("Id")
                        .HasName("pk_class_core_traits");

                    b.HasIndex("CharacterClassId")
                        .IsUnique()
                        .HasDatabaseName("ux_class_core_traits_class");

                    b.ToTable("class_core_traits", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_class_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int?>("ProficiencyBonus")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency_bonus");

                    b.HasKey("Id")
                        .HasName("pk_class_levels");

                    b.HasIndex("CharacterClassId", "Level")
                        .IsUnique()
                        .HasDatabaseName("ux_class_levels_class_level");

                    b.ToTable("class_levels", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassLevelSpellSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_level_id");

                    b.Property<int>("Slots")
                        .HasColumnType("integer")
                        .HasColumnName("slots");

                    b.Property<int>("SpellLevel")
                        .HasColumnType("integer")
                        .HasColumnName("spell_level");

                    b.HasKey("Id")
                        .HasName("pk_class_level_spell_slots");

                    b.HasIndex("ClassLevelId", "SpellLevel")
                        .IsUnique()
                        .HasDatabaseName("ux_class_level_spell_slots_level_spell_level");

                    b.ToTable("class_level_spell_slots", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassPrimaryAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AbilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("ability_id");

                    b.Property<Guid>("CharacterClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_class_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_class_primary_abilities");

                    b.HasIndex("CharacterClassId", "AbilityId")
                        .IsUnique()
                        .HasDatabaseName("ux_class_primary_abilities_class_ability");

                    b.HasIndex("CharacterClassId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_class_primary_abilities_class_sort");

                    b.ToTable("class_primary_abilities", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassProficiencyGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_level_id");

                    b.Property<Guid>("ProficiencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("proficiency_id");

                    b.HasKey("Id")
                        .HasName("pk_class_proficiency_grants");

                    b.HasIndex("ClassLevelId", "ProficiencyId")
                        .IsUnique()
                        .HasDatabaseName("ux_class_proficiency_grants_level_proficiency");

                    b.ToTable("class_proficiency_grants", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassSpellcastingLevelRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CasterLevel")
                        .HasColumnType("integer")
                        .HasColumnName("caster_level");

                    b.Property<int>("ClassLevel")
                        .HasColumnType("integer")
                        .HasColumnName("class_level");

                    b.Property<Guid>("ClassSpellcastingProgressionId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_spellcasting_progression_id");

                    b.HasKey("Id")
                        .HasName("pk_class_spellcasting_level_rules");

                    b.HasIndex("ClassSpellcastingProgressionId", "ClassLevel")
                        .IsUnique()
                        .HasDatabaseName("ux_class_spellcasting_level_rules_progression_level");

                    b.ToTable("class_spellcasting_level_rules", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassSpellcastingProgression", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_class_id");

                    b.Property<Guid?>("SpellcastingAbilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("spellcasting_ability_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_class_spellcasting_progressions");

                    b.HasIndex("CharacterClassId")
                        .IsUnique()
                        .HasDatabaseName("ux_class_spellcasting_progressions_class");

                    b.ToTable("class_spellcasting_progressions", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassWeaponMasteryCountByLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_level_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.HasKey("Id")
                        .HasName("pk_class_weapon_mastery_count_by_level");

                    b.HasIndex("ClassLevelId")
                        .IsUnique()
                        .HasDatabaseName("ux_class_weapon_mastery_count_by_level_level");

                    b.ToTable("class_weapon_mastery_count_by_level", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.SubclassFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterSubclassId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_subclass_id");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.HasKey("Id")
                        .HasName("pk_subclass_features");

                    b.HasIndex("CharacterSubclassId", "FeatureId", "Level")
                        .IsUnique()
                        .HasDatabaseName("ux_subclass_features_subclass_feature_level");

                    b.ToTable("subclass_features", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.BackgroundFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_id");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("background_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.HasKey("Id")
                        .HasName("pk_background_features");

                    b.HasIndex("SourceEntityId", "FeatureId", "Level")
                        .IsUnique()
                        .HasDatabaseName("ux_background_features_source_feature_level");

                    b.ToTable("background_features", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.ChoiceOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChoiceSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("choice_set_id");

                    b.Property<string>("DisplayText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("display_text");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_choice_options");

                    b.HasIndex("ChoiceSetId");

                    b.ToTable("choice_options", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.ChoiceSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("code");

                    b.Property<int>("MaximumChoices")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_choices");

                    b.Property<int>("MinimumChoices")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_choices");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_entity_id");

                    b.Property<string>("SourceEntityKind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_entity_kind");

                    b.HasKey("Id")
                        .HasName("pk_choice_sets");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_choice_sets_code");

                    b.HasIndex("SourceEntityKind", "SourceEntityId")
                        .HasDatabaseName("ix_choice_sets_source_entity");

                    b.ToTable("choice_sets", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.ChoiceSetFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChoiceSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("choice_set_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_choice_set_filters");

                    b.HasIndex("ChoiceSetId");

                    b.ToTable("choice_set_filters", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.ClassLevelFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_id");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_level_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.HasKey("Id")
                        .HasName("pk_class_level_features");

                    b.HasIndex("SourceEntityId", "FeatureId", "Level")
                        .IsUnique()
                        .HasDatabaseName("ux_class_level_features_source_feature_level");

                    b.ToTable("class_level_features", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.EffectSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_effect_schemas");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_effect_schemas_code");

                    b.ToTable("effect_schemas", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.EffectSchemaField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("code");

                    b.Property<Guid>("EffectSchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("effect_schema_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_effect_schema_fields");

                    b.HasIndex("EffectSchemaId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_effect_schema_fields_schema_code");

                    b.ToTable("effect_schema_fields", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.EntityPrerequisite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_kind");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operator");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("target");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_entity_prerequisites");

                    b.HasIndex("EntityKind", "EntityId")
                        .HasDatabaseName("ix_entity_prerequisites_entity");

                    b.ToTable("entity_prerequisites", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.FeatFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_id");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("feat_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.HasKey("Id")
                        .HasName("pk_feat_features");

                    b.HasIndex("SourceEntityId", "FeatureId", "Level")
                        .IsUnique()
                        .HasDatabaseName("ux_feat_features_source_feature_level");

                    b.ToTable("feat_features", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<int?>("LevelRequirement")
                        .HasColumnType("integer")
                        .HasColumnName("level_requirement");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("RuleSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_source_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_features");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_features_code");

                    b.HasIndex("SourceVersionId")
                        .HasDatabaseName("ix_features_source_version_id");

                    b.ToTable("features", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.FeatureEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EffectSchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("effect_schema_id");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_id");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("target");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_feature_effects");

                    b.HasIndex("FeatureId")
                        .HasDatabaseName("ix_feature_effects_feature_id");

                    b.ToTable("feature_effects", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.FeatureEffectCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FeatureEffectId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_effect_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_feature_effect_conditions");

                    b.HasIndex("FeatureEffectId");

                    b.ToTable("feature_effect_conditions", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.FeatureEffectFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EffectSchemaFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("effect_schema_field_id");

                    b.Property<Guid>("FeatureEffectId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_effect_id");

                    b.HasKey("Id")
                        .HasName("pk_feature_effect_field_values");

                    b.HasIndex("FeatureEffectId", "EffectSchemaFieldId")
                        .IsUnique()
                        .HasDatabaseName("ux_feature_effect_field_values_effect_field");

                    b.ToTable("feature_effect_field_values", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Features.SpeciesFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_id");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.HasKey("Id")
                        .HasName("pk_species_features");

                    b.HasIndex("SourceEntityId", "FeatureId", "Level")
                        .IsUnique()
                        .HasDatabaseName("ux_species_features_source_feature_level");

                    b.ToTable("species_features", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.Ability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("RuleSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_source_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_abilities");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_abilities_code");

                    b.HasIndex("SourceVersionId")
                        .HasDatabaseName("ix_abilities_source_version_id");

                    b.ToTable("abilities", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.AbilityScoreMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("RuleSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_source_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_ability_score_methods");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_ability_score_methods_code");

                    b.HasIndex("SourceVersionId")
                        .HasDatabaseName("ix_ability_score_methods_source_version_id");

                    b.ToTable("ability_score_methods", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.AbilityScoreMethodRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AbilityScoreMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("ability_score_method_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<int?>("NumericValue")
                        .HasColumnType("integer")
                        .HasColumnName("numeric_value");

                    b.Property<string>("TextValue")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("text_value");

                    b.HasKey("Id")
                        .HasName("pk_ability_score_method_rules");

                    b.HasIndex("AbilityScoreMethodId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_ability_score_method_rules_method_code");

                    b.ToTable("ability_score_method_rules", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.AbilityScorePointBuyCost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AbilityScoreMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("ability_score_method_id");

                    b.Property<int>("Cost")
                        .HasColumnType("integer")
                        .HasColumnName("cost");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_ability_score_point_buy_costs");

                    b.HasIndex("AbilityScoreMethodId", "Score")
                        .IsUnique()
                        .HasDatabaseName("ux_ability_score_point_buy_costs_method_score");

                    b.ToTable("ability_score_point_buy_costs", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.AbilityScoreRollRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AbilityScoreMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("ability_score_method_id");

                    b.Property<int>("DiceQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("dice_quantity");

                    b.Property<int>("DieSize")
                        .HasColumnType("integer")
                        .HasColumnName("die_size");

                    b.Property<int?>("DropLowestQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("drop_lowest_quantity");

                    b.Property<int>("KeepHighestQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("keep_highest_quantity");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer")
                        .HasColumnName("repetitions");

                    b.HasKey("Id")
                        .HasName("pk_ability_score_roll_rules");

                    b.HasIndex("AbilityScoreMethodId")
                        .IsUnique()
                        .HasDatabaseName("ux_ability_score_roll_rules_method");

                    b.ToTable("ability_score_roll_rules", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.AbilityScoreStandardValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AbilityScoreMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("ability_score_method_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_ability_score_standard_values");

                    b.HasIndex("AbilityScoreMethodId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_ability_score_standard_values_method_position");

                    b.ToTable("ability_score_standard_values", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.ArmorTrainingCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("RuleSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_source_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_armor_training_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_armor_training_categories_code");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_armor_training_categories_sort_order");

                    b.ToTable("armor_training_categories", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.HitDie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Die")
                        .HasColumnType("integer")
                        .HasColumnName("die");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("RuleSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_source_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_hit_dice");

                    b.HasIndex("Die")
                        .IsUnique()
                        .HasDatabaseName("ux_hit_dice_die");

                    b.ToTable("hit_dice", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("RuleSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_source_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_languages_code");

                    b.HasIndex("SourceVersionId")
                        .HasDatabaseName("ix_languages_source_version_id");

                    b.ToTable("languages", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.Proficiency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<Guid>("RuleSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_source_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_proficiencies");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_proficiencies_code");

                    b.HasIndex("RelatedEntityId")
                        .HasDatabaseName("ix_proficiencies_related_entity_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_proficiencies_type");

                    b.ToTable("proficiencies", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DefaultAbilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_ability_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("RuleSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_source_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_skills_code");

                    b.HasIndex("DefaultAbilityId")
                        .HasDatabaseName("ix_skills_default_ability_id");

                    b.HasIndex("SourceVersionId")
                        .HasDatabaseName("ix_skills_source_version_id");

                    b.ToTable("skills", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Sources.RuleSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("RulesetId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruleset_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_rule_sources");

                    b.HasIndex("RulesetId")
                        .HasDatabaseName("ix_rule_sources_ruleset_id");

                    b.HasIndex("RulesetId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_rule_sources_ruleset_code");

                    b.ToTable("rule_sources", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Sources.Ruleset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_rulesets");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_rulesets_code");

                    b.ToTable("rulesets", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Sources.SourceVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ImportStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("import_status");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateOnly>("PublicationDate")
                        .HasColumnType("date")
                        .HasColumnName("publication_date");

                    b.Property<Guid>("RuleSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_source_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_source_versions");

                    b.HasIndex("RuleSourceId")
                        .HasDatabaseName("ix_source_versions_rule_source_id");

                    b.HasIndex("RuleSourceId", "IsCurrent")
                        .IsUnique()
                        .HasDatabaseName("ux_source_versions_current_per_source")
                        .HasFilter("is_current = true");

                    b.HasIndex("RuleSourceId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_source_versions_source_version");

                    b.ToTable("source_versions", "compendium");
                });

            modelBuilder.Entity("Compendium.Infra.Persistence.Integration.IntegrationInbox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("consumer_name");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("event_name");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_integration_inbox");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_integration_inbox_status");

                    b.HasIndex("EventId", "ConsumerName")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_inbox_event_consumer");

                    b.ToTable("integration_inbox", "compendium");
                });

            modelBuilder.Entity("Compendium.Infra.Persistence.Integration.IntegrationOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("aggregate_type");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("event_name");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_integration_outbox");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("ix_integration_outbox_aggregate_id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_outbox_event_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_integration_outbox_status");

                    b.ToTable("integration_outbox", "compendium");
                });

            modelBuilder.Entity("Compendium.Infra.Persistence.Integration.IntegrationOutboxField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean")
                        .HasColumnName("boolean_value");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EnumValue")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("enum_value");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("field_type");

                    b.Property<decimal?>("NumberValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("number_value");

                    b.Property<Guid>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("ReferenceValue")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("reference_value");

                    b.Property<string>("TextValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text_value");

                    b.HasKey("Id")
                        .HasName("pk_integration_outbox_fields");

                    b.HasIndex("OutboxId")
                        .HasDatabaseName("ix_integration_outbox_fields_outbox_id");

                    b.HasIndex("OutboxId", "FieldName")
                        .HasDatabaseName("ix_integration_outbox_fields_outbox_field");

                    b.ToTable("integration_outbox_fields", "compendium");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassCoreTraits", b =>
                {
                    b.HasOne("Compendium.Domain.Classes.CharacterClass", null)
                        .WithOne("CoreTraits")
                        .HasForeignKey("Compendium.Domain.Classes.ClassCoreTraits", "CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassLevel", b =>
                {
                    b.HasOne("Compendium.Domain.Classes.CharacterClass", null)
                        .WithMany("Levels")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassLevelSpellSlot", b =>
                {
                    b.HasOne("Compendium.Domain.Classes.ClassLevel", null)
                        .WithMany("SpellSlots")
                        .HasForeignKey("ClassLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassPrimaryAbility", b =>
                {
                    b.HasOne("Compendium.Domain.Classes.CharacterClass", null)
                        .WithMany("PrimaryAbilities")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassProficiencyGrant", b =>
                {
                    b.HasOne("Compendium.Domain.Classes.ClassLevel", null)
                        .WithMany("ProficiencyGrants")
                        .HasForeignKey("ClassLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassSpellcastingLevelRule", b =>
                {
                    b.HasOne("Compendium.Domain.Classes.ClassSpellcastingProgression", null)
                        .WithMany("LevelRules")
                        .HasForeignKey("ClassSpellcastingProgressionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassSpellcastingProgression", b =>
                {
                    b.HasOne("Compendium.Domain.Classes.CharacterClass", null)
                        .WithOne("SpellcastingProgression")
                        .HasForeignKey("Compendium.Domain.Classes.ClassSpellcastingProgression", "CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassWeaponMasteryCountByLevel", b =>
                {
                    b.HasOne("Compendium.Domain.Classes.ClassLevel", null)
                        .WithMany("WeaponMasteryCounts")
                        .HasForeignKey("ClassLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Classes.SubclassFeature", b =>
                {
                    b.HasOne("Compendium.Domain.Classes.CharacterSubclass", null)
                        .WithMany("Features")
                        .HasForeignKey("CharacterSubclassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Features.ChoiceOption", b =>
                {
                    b.HasOne("Compendium.Domain.Features.ChoiceSet", null)
                        .WithMany("Options")
                        .HasForeignKey("ChoiceSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Features.ChoiceSetFilter", b =>
                {
                    b.HasOne("Compendium.Domain.Features.ChoiceSet", null)
                        .WithMany("Filters")
                        .HasForeignKey("ChoiceSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Compendium.Domain.Features.TypedMechanicalValue", "Value", b1 =>
                        {
                            b1.Property<Guid>("ChoiceSetFilterId")
                                .HasColumnType("uuid");

                            b1.Property<bool?>("BooleanValue")
                                .HasColumnType("boolean")
                                .HasColumnName("boolean_value");

                            b1.Property<string>("EnumValue")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("enum_value");

                            b1.Property<decimal?>("NumericValue")
                                .HasColumnType("numeric")
                                .HasColumnName("numeric_value");

                            b1.Property<Guid?>("ReferenceId")
                                .HasColumnType("uuid")
                                .HasColumnName("ref_id");

                            b1.Property<string>("TextValue")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("text_value");

                            b1.Property<string>("ValueType")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("value_type");

                            b1.HasKey("ChoiceSetFilterId");

                            b1.ToTable("choice_set_filters", "compendium");

                            b1.WithOwner()
                                .HasForeignKey("ChoiceSetFilterId");
                        });

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Features.EffectSchemaField", b =>
                {
                    b.HasOne("Compendium.Domain.Features.EffectSchema", null)
                        .WithMany("Fields")
                        .HasForeignKey("EffectSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Features.EntityPrerequisite", b =>
                {
                    b.OwnsOne("Compendium.Domain.Features.TypedMechanicalValue", "Value", b1 =>
                        {
                            b1.Property<Guid>("EntityPrerequisiteId")
                                .HasColumnType("uuid");

                            b1.Property<bool?>("BooleanValue")
                                .HasColumnType("boolean")
                                .HasColumnName("boolean_value");

                            b1.Property<string>("EnumValue")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("enum_value");

                            b1.Property<decimal?>("NumericValue")
                                .HasColumnType("numeric")
                                .HasColumnName("numeric_value");

                            b1.Property<Guid?>("ReferenceId")
                                .HasColumnType("uuid")
                                .HasColumnName("ref_id");

                            b1.Property<string>("TextValue")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("text_value");

                            b1.Property<string>("ValueType")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("value_type");

                            b1.HasKey("EntityPrerequisiteId");

                            b1.ToTable("entity_prerequisites", "compendium");

                            b1.WithOwner()
                                .HasForeignKey("EntityPrerequisiteId");
                        });

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Features.FeatureEffect", b =>
                {
                    b.HasOne("Compendium.Domain.Features.Feature", null)
                        .WithMany("Effects")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Features.FeatureEffectCondition", b =>
                {
                    b.HasOne("Compendium.Domain.Features.FeatureEffect", null)
                        .WithMany("Conditions")
                        .HasForeignKey("FeatureEffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Compendium.Domain.Features.TypedMechanicalValue", "Value", b1 =>
                        {
                            b1.Property<Guid>("FeatureEffectConditionId")
                                .HasColumnType("uuid");

                            b1.Property<bool?>("BooleanValue")
                                .HasColumnType("boolean")
                                .HasColumnName("boolean_value");

                            b1.Property<string>("EnumValue")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("enum_value");

                            b1.Property<decimal?>("NumericValue")
                                .HasColumnType("numeric")
                                .HasColumnName("numeric_value");

                            b1.Property<Guid?>("ReferenceId")
                                .HasColumnType("uuid")
                                .HasColumnName("ref_id");

                            b1.Property<string>("TextValue")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("text_value");

                            b1.Property<string>("ValueType")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("value_type");

                            b1.HasKey("FeatureEffectConditionId");

                            b1.ToTable("feature_effect_conditions", "compendium");

                            b1.WithOwner()
                                .HasForeignKey("FeatureEffectConditionId");
                        });

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Features.FeatureEffectFieldValue", b =>
                {
                    b.HasOne("Compendium.Domain.Features.FeatureEffect", null)
                        .WithMany("FieldValues")
                        .HasForeignKey("FeatureEffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Compendium.Domain.Features.TypedMechanicalValue", "Value", b1 =>
                        {
                            b1.Property<Guid>("FeatureEffectFieldValueId")
                                .HasColumnType("uuid");

                            b1.Property<bool?>("BooleanValue")
                                .HasColumnType("boolean")
                                .HasColumnName("boolean_value");

                            b1.Property<string>("EnumValue")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("enum_value");

                            b1.Property<decimal?>("NumericValue")
                                .HasColumnType("numeric")
                                .HasColumnName("numeric_value");

                            b1.Property<Guid?>("ReferenceId")
                                .HasColumnType("uuid")
                                .HasColumnName("ref_id");

                            b1.Property<string>("TextValue")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("text_value");

                            b1.Property<string>("ValueType")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("value_type");

                            b1.HasKey("FeatureEffectFieldValueId");

                            b1.ToTable("feature_effect_field_values", "compendium");

                            b1.WithOwner()
                                .HasForeignKey("FeatureEffectFieldValueId");
                        });

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.AbilityScoreMethodRule", b =>
                {
                    b.HasOne("Compendium.Domain.Fundamentals.AbilityScoreMethod", null)
                        .WithMany("Rules")
                        .HasForeignKey("AbilityScoreMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.AbilityScorePointBuyCost", b =>
                {
                    b.HasOne("Compendium.Domain.Fundamentals.AbilityScoreMethod", null)
                        .WithMany("PointBuyCosts")
                        .HasForeignKey("AbilityScoreMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.AbilityScoreRollRule", b =>
                {
                    b.HasOne("Compendium.Domain.Fundamentals.AbilityScoreMethod", null)
                        .WithMany("RollRules")
                        .HasForeignKey("AbilityScoreMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.AbilityScoreStandardValue", b =>
                {
                    b.HasOne("Compendium.Domain.Fundamentals.AbilityScoreMethod", null)
                        .WithMany("StandardValues")
                        .HasForeignKey("AbilityScoreMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compendium.Infra.Persistence.Integration.IntegrationOutboxField", b =>
                {
                    b.HasOne("Compendium.Infra.Persistence.Integration.IntegrationOutbox", "Outbox")
                        .WithMany("Fields")
                        .HasForeignKey("OutboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integration_outbox_fields_outbox");

                    b.Navigation("Outbox");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.CharacterClass", b =>
                {
                    b.Navigation("CoreTraits");

                    b.Navigation("Levels");

                    b.Navigation("PrimaryAbilities");

                    b.Navigation("SpellcastingProgression");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.CharacterSubclass", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassLevel", b =>
                {
                    b.Navigation("ProficiencyGrants");

                    b.Navigation("SpellSlots");

                    b.Navigation("WeaponMasteryCounts");
                });

            modelBuilder.Entity("Compendium.Domain.Classes.ClassSpellcastingProgression", b =>
                {
                    b.Navigation("LevelRules");
                });

            modelBuilder.Entity("Compendium.Domain.Features.ChoiceSet", b =>
                {
                    b.Navigation("Filters");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Compendium.Domain.Features.EffectSchema", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Compendium.Domain.Features.Feature", b =>
                {
                    b.Navigation("Effects");
                });

            modelBuilder.Entity("Compendium.Domain.Features.FeatureEffect", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("Compendium.Domain.Fundamentals.AbilityScoreMethod", b =>
                {
                    b.Navigation("PointBuyCosts");

                    b.Navigation("RollRules");

                    b.Navigation("Rules");

                    b.Navigation("StandardValues");
                });

            modelBuilder.Entity("Compendium.Infra.Persistence.Integration.IntegrationOutbox", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
